send_message:
  name: Send Message
  description: Sends a Message (iMessage / RCS / MMS / SMS) via BlueBubbles.
  fields:
    addresses:
      name: Address(es)
      description: The address(es) to send to. Multiple addresses can be separated by commas or semicolons.
      required: true
      example: "+15558675309, a.contact@me.com"
      selector:
        text:
    message:
      name: Message
      description: The message to send.
      required: true
      example: "Hello!"
      selector:
        text: